---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solid-fiesta-consumer
  labels:
    app: solid-fiesta-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solid-fiesta-consumer
  template:
    metadata:
      labels:
        app: solid-fiesta-consumer
    spec:
      containers:
        - name: consumer
          image: hsmtkk/solid-fiesta: latest
          imagePullPolicy: Always
          command:
            - /usr/local/bin/consumer
          env:
            - name: NATS_URL
              value: nats://solid-fiesta-nats:4222
            - name: NATS_SUBJECT
              value: test
