---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solid-fiesta-consumer
  labels:
    app: solid-fiesta-consumer
  annotations:
    prometheus.io/scrape: true
    prometheus.io/path: /metrics
    prometheus.io/port: 9123
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solid-fiesta-consumer
  template:
    metadata:
      labels:
        app: solid-fiesta-consumer
    spec:
      containers:
        - name: consumer
          image: hsmtkk/solid-fiesta:latest
          imagePullPolicy: Always
          command:
            - /usr/local/bin/consumer
          env:
            - name: EXPORTER_PORT
              value: "9123"
            - name: NATS_URL
              value: nats://solid-fiesta-nats:4222
            - name: NATS_SUBJECT
              value: test
          ports:
            - containerPort: 9123
          startupProbe:
            httpGet:
              path: /metrics
              port: 9123
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9123
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9123
