---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solid-fiesta-prometheus
  labels:
    app: solid-fiesta-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solid-fiesta-prometheus
  template:
    metadata:
      labels:
        app: solid-fiesta-prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          startupProbe:
            httpGet:
              path: /metrics
              port: 9090
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9090
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: solid-fiesta-prometheus
spec:
  type: ClusterIP
  selector:
    app: solid-fiesta-prometheus
  ports:
  - protocol: TCP
    port: 9090
