---
version: "3.8"
services:
  producer:
    image: hsmtkk/solid-fiesta:latest
    command:
      - /usr/local/bin/producer
    environment:
      EXPORTER_PORT: 9123
      NATS_URL: nats://nats:4222
      NATS_SUBJECT: test
      INTERVAL_SECONDS: "1"
  nats:
    image: nats:latest
  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    command:
      - -varz
      - http://nats:8222
  consumer:
    image: hsmtkk/solid-fiesta:latest
    command:
      - /usr/local/bin/consumer
    environment:
      EXPORTER_PORT: 9123
      NATS_URL: nats://nats:4222
      NATS_SUBJECT: test
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
