---
version: "3.8"
services:
  producer:
    image: hsmtkk/solid-fiesta:latest
    command:
      - /usr/local/bin/producer
    environment:
      EXPORTER_PORT: 9123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CHANNEL: test
      INTERVAL_SECONDS: "5"
  nats:
    image: redis:latest
  consumer:
    image: hsmtkk/solid-fiesta:latest
    command:
      - /usr/local/bin/consumer
    environment:
      EXPORTER_PORT: 9123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CHANNEL: test
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
